### ISSUE TITLE
chore: rename differ.rs crate to another name since differ is already taken

### ISSUE THREAD

**Issue by neoncitylights** [nlp-rs/differ.rs#44]
Needs some new ideas... maybe `typediff` instead? @notalfredo

**Comment by notalfredo** [comment]
~~I like that name what do you think about `typesim` @neoncitylights~~ I like `typediff` more

**Comment by neoncitylights** [comment]
Ah, not just yet, still need to write a PR to rename the code internally :P

**Comment by notalfredo** [comment]
> Ah, not just yet, still need to write a PR to rename the code internally :P

I was going to handle that with issue 45 but go ahead xP *I thought it was weird you did not mention it*

**Comment by neoncitylights** [comment]
Well they're different issues and thus out-of-scope IMO. Blocking the initial prototype/design of `semantic_typediff` should not block renaming `differ` to `typediff` (which would happen if both changes happened in a single PR), that can be done by itself and merged much quicker
