### ISSUE TITLE
chore: where should the proposed addition to NLP rust go

### ISSUE THREAD

**Issue by notalfredo** [nlp-rs/differ.rs#45]
@neoncitylights proposed some functionality such as 

Word::new("woman").as_plural() // "women"
Word::new("men").as_singular() // "man"
Word::new("walking").as_morphemes() // Vec["Walk", "-ing"]
Word::new("walking").as_lemma

Should we add this to differ.rs ie ( the monorepo ) or should we put it in a separate directory ?

**Comment by neoncitylights** [comment]
How about under `crates/semantic_typediff`?

**Comment by notalfredo** [comment]
thats fine ill go ahead and get that started
