### ISSUE TITLE
Duplicate code between `diff()` and `distance()`

### ISSUE THREAD

**Issue by neoncitylights** [nlp-rs/differ.rs#9]
The initial implementation seems to have caused some duplicate code between both methods defined for the implementations of the `StringDiffAlgorithm` trait. 

One reason the `distance()` method exists is that it's less memory-intensive. It always returns a `usize` type (statically-sized), since it's guaranteed to either be 32-bit or 64-bit integer. as creating a struct requires allocating memory. 

`diff()` allocates more memory since it's creating instances of `StringDiffOp`s, and also returns a vector, where vectors are a DST (dynamically-sized type), and therefore heap-allocated.

----

Is there a way we can deduplicate the code? The alternative is to let the library user call the `len()` method, like:
```rs
let hamming = HammingDistance {};
let distance: usize = hamming.diff().len();
```

What happens though, as mentioned above, is that if they only *need* the distance, then it's allocating memory that'll never be used. On the other hand, it'll be a maintenance burden to manage both duplicate implementations, and it'll be easier for bugs to pop up. Thoughts?

**Comment by notalfredo** [comment]
I like this idea. Another alternative I can also think of is that we can make diff return the vector AND also the usize distance ? the only downside to this would be that now the user has to handle two variables when they might only need one. While the suggestion you provided the user can choose just to get the length or the vector. I think maybe the suggestion you made might be better. Thoughts ?

Either way would require some changes to the readme instructions not a problem tho.
